### ISSUE TITLE
Codeception 2.1 support

### ISSUE THREAD

**Issue by meare** [redmatter/Codeception-MultiDb#1]
First of all, thanks for this extension, I really miss this feature in Db module now.

Do you plan to make it compatible with Codeception 2.1?

**Comment by codemedic** [comment]
We do have plans to make it 2.1 compatible; started working on it recently.
No ETA yet; will keep you posted.

**Comment by codemedic** [comment]
@sunfreakz .. please can you checkout version "2.0.x-dev"

**Comment by meare** [comment]
@codemedic seems like it works fine, thank you!

**Comment by codemedic** [comment]
Great!

I will close this bug for now; if you find any bugs with v2.0; please do log them.
