### ISSUE TITLE
Invalid default 'UTC' timezone

### ISSUE THREAD

**Issue by edno** [redmatter/Codeception-MultiDb#15]
On CentOs, the timezone table is not created on MySQL and then the PDO connection failed with following error:

```
[ModuleException] Codeception\Extension\MultiDb: SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: 'UTC' while creating PDO connection [PDOException]
```

Recommended to use 'SYSTEM' or '+00:00'

**Comment by codemedic** [comment]
@edno thanks for the bug report. Please do submit a PR for your change.

**Comment by edno** [comment]
Done PR #16

**Comment by edno** [comment]
PR? no PR?

**Comment by FractalMind** [comment]
modules:
        Codeception\Extension\MultiDb:
            timezone: "+00:00"
