### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by TuningGuide** [redmatter/Codeception-MultiDb#2]
$ sudo composer require "natterbox/codeception-multidb: 2.0.x-dev"
Password:
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package natterbox/codeception-multidb could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by TuningGuide** [comment]
I just have to add a @dev right?
so
sudo composer require "natterbox/codeception-multidb: 2.0.x-dev@dev"

**Comment by codemedic** [comment]
@TuningGuide Thanks for taking time to log the issue.

I have updated the README and hence the packagist page.
https://packagist.org/packages/natterbox/codeception-multidb
