### ISSUE TITLE
DemoCest Example

### ISSUE THREAD

**Issue by TuningGuide** [redmatter/Codeception-MultiDb#3]
In you example you use $I->amConnectedToDb('Primary') but afterwards you use PrimaryDB.User shouldn't it be Primary.User?

**Comment by codemedic** [comment]
@TuningGuide Perhaps the example is a little bit confusing.
If you look at https://github.com/natterbox/Codeception-MultiDb/blob/2.0/examples/tests/acceptance.suite.yml `Primary` is the connector name and `PrimaryDb` is the database name.
In the invocation of `amConnectedToDb()` you are actually specifying the connector / DSN identifier, which in the case of the example is `Primary`.

PS: Feel free to edit the example to make it more understandable and make a PR.

**Comment by TuningGuide** [comment]
Does this extension also work for tables with no primary key?

**Comment by codemedic** [comment]
Absolutely; have a look at the example ( recently updated ) /examples/tests/acceptance/DemoCest.php on Line 69.
The primary key is really used for setting up cleanup; so it can really be any field that you know for sure can be used to delete records that you have just inserted.

Use the `--debug` option when you run the demo test, to see what is going on behind the scene.

```
 vendor/bin/codecept run --debug
```
